spring:
  application:
    name: kotlin-restful-api
  liquibase:
    enabled: true
    change-log: db/changelog/main.xml
  datasource:
    url: jdbc:postgresql://localhost:5432/dev
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
